export const CONFIG = {
    TILE: 32,
    PLAYER_SPEED: 2.5,
    PLAYER_RADIUS: 8,
    SEEKER_VISION_RANGE: 180,
    SEEKER_VISION_ANGLE: Math.PI / 2.5,  
    HIDER_VISION_RANGE: 120,
    HIDER_VISION_ANGLE: Math.PI / 2,     
    FREEZE_SECS: 10,
    MATCH_SECS: 130,
    SCORE_TICKS: 60,
    FPS: 60,
};
