export const CONFIG = {
    TILE: 32,
    PLAYER_SPEED: 2.5,
    PLAYER_RADIUS: 8,
    SEEKER_VISION_RANGE: 180,
    SEEKER_VISION_ANGLE: Math.PI / 2.5,  
    HIDER_VISION_RANGE: 120,
    HIDER_VISION_ANGLE: Math.PI / 2,     
    FREEZE_SECS: 10,
    MATCH_SECS: 120,
    SCORE_TICKS: 60,
    FPS: 60,
};

export const CONFIG_IA = {
    MUTATION_RATE: 0.1,
    RAYS_PER_PLAYER: 7,
    ACTIVATION_THRESHOLD: 0.5,
    PERCENTAGE_SURVIVE: 0.3,
}